name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write  # Concede permissão de escrita para o GitHub Actions

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: heytorpimentell
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Corrigido (sem a vírgula)
